import test from 'node:test';import assert from 'node:assert/strict';
import {courses,fresh,normalise,score,completed,certificateEligible,MAX_FAILED_ATTEMPTS} from '../dist/content.js';
test('courses have complete variable assessments',()=>{assert.equal(courses.length,14);assert.deepEqual(courses.map(c=>c.questions.length),[18,20,20,20,22,22,20,20,20,20,22,20,18,20]);assert.deepEqual(courses.map(c=>c.lessons.length),Array(14).fill(7));assert.deepEqual(courses.filter(c=>c.advanced).map(c=>c.id),['mental-health','health-safety','trauma-informed','wellbeing']);for(const c of courses){assert.equal(c.passMark,Math.ceil(c.questions.length*.75));assert.ok(c.testSeconds>=1200);const coverage=Array(c.lessons.length).fill(0);for(const q of c.questions){assert.ok(Number.isInteger(q.lesson)&&q.lesson>=0&&q.lesson<c.lessons.length);coverage[q.lesson]++}assert.ok(coverage.every(n=>n>=2))}});
test('every assessment scores exactly',()=>{for(const c of courses){const a=c.questions.map(q=>q.answer);assert.equal(score(a,c),c.questions.length);assert.equal(score(a.map((x,i)=>(x+1)%c.questions[i].options.length),c),0)}});
test('course completion is independent',()=>{const state=fresh(),c=courses[1],s=state.courseStates[c.id];s.read=c.lessons.map((_,i)=>i);s.best=c.passMark;assert.equal(completed(s,c),true);assert.equal(certificateEligible(state),false)});
test('certificate requires every course',()=>{const state=fresh();for(const c of courses){const s=state.courseStates[c.id];s.read=c.lessons.map((_,i)=>i);s.best=c.passMark}assert.equal(certificateEligible(state),true)});
test('version 3 progress migrates',()=>{const s=normalise({version:3,read:[0,1],lesson:2,answers:[],records:[]});assert.deepEqual(s.courseStates.teamwork.read,[0,1]);assert.equal(s.version,4)});
test('invalid positions are constrained',()=>{const raw=fresh(),c=courses[2];raw.courseStates[c.id]={read:[0],lesson:99,question:99,failedAttempts:99,answers:[]};const s=normalise(raw).courseStates[c.id];assert.equal(s.lesson,1);assert.equal(s.question,c.questions.length-1);assert.equal(s.failedAttempts,MAX_FAILED_ATTEMPTS)});
test('history records survive',()=>{const raw=fresh(),c=courses[3];raw.courseStates[c.id].records=[{score:8,passed:false,completedAt:1,attempt:1},{score:12,passed:true,completedAt:2,attempt:2}];assert.equal(normalise(raw).courseStates[c.id].records.length,2)});
import {emailsFromText,rowFromCourseState,stateFromProgressRows,canAccessCourses,canViewAdmin,needsInviteGate,supabaseConfigured} from '../dist/supabase-client.js';

test('invite email parsing normalises and deduplicates addresses',()=>{assert.deepEqual(emailsFromText(' A@Example.COM, bad  b@example.com\na@example.com; c@test.org '),['a@example.com','b@example.com','c@test.org'])});

test('local course progress maps to and from Supabase rows',()=>{const c=courses[0],state=fresh(),s=state.courseStates[c.id];s.read=c.lessons.map((_,i)=>i);s.best=c.passMark;s.failedAttempts=1;s.question=3;s.answers=Array(c.questions.length).fill(null);s.answers[0]=c.questions[0].answer;s.submitted=true;s.testStartedAt=Date.UTC(2026,0,1);s.testExpired=false;const row=rowFromCourseState(c,s,'00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000002');assert.equal(row.course_id,c.id);assert.equal(row.best,c.passMark);assert.equal(row.failed_attempts,1);assert.equal(row.test_started_at,'2026-01-01T00:00:00.000Z');const restored=stateFromProgressRows([row]).courseStates[c.id];assert.deepEqual(restored.read,c.lessons.map((_,i)=>i));assert.equal(restored.best,c.passMark);assert.equal(restored.failedAttempts,1);assert.equal(restored.submitted,true)});


test('auth guard helpers distinguish admin, user and waiting states',()=>{const admin={user:{id:'u1'},membership:{role:'admin',status:'active'}};const user={user:{id:'u2'},membership:{role:'user',status:'active'}};const waiting={user:{id:'u3'},membership:null};assert.equal(canViewAdmin(admin),true);assert.equal(canViewAdmin(user),false);assert.equal(canAccessCourses(user),true);assert.equal(canAccessCourses(waiting),!supabaseConfigured);assert.equal(needsInviteGate(waiting),supabaseConfigured)});
